version: '3.9'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app

  sender:
    build:
      context: ./sender
    volumes:
      - ./data:/data
    depends_on:
      - server

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - server
    volumes:
      - ./frontend:/usr/share/nginx/html
